export const DIRECT_SET_FORM_VALUE = 'DIRECT_SET_FORM_VALUE'
export const DECREMENT2 = 'DECREMENT2'
export const SET_DELIVERY_DETAIL = 'SET_DELIVERY_DETAIL'
export const SET_CHANGE_ACTION = 'SET_CHANGE_ACTION'
